### ISSUE TITLE
Database Migrate does not populate DB

### ISSUE THREAD

**Issue by andywatermarkmedical** [aws-samples/amazon-dotnet-api-to-lambda#1]
The example database is not populated with data.

Installed as instructed.
Ran the app as instructed
use the browser to call curl ( /booking/customer/jamesuk )
returns an empty array

context.Database.Migrate()  seem to run fine.  Absolution no errors.

**Comment by jeastham1993** [comment]
Thanks for the feedback @andywatermarkmedical ,I've updated the documentation to provide clearer instructions.
